spring:
  application:
    name: AlfaBalls
    version: 0.0.1
  profiles:
    active: dev

---
jwt:
  secret: "5367566859703373367639792F423F452848284D6251655468576D5A71347437"
  access-token-expiration-ms: 36000000   # 20 сек
  refresh-token-expiration-ms: 604800000  # 40 сек


---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:dev_db
    username: dev
    password: dev
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/alfaballs
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create